---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
  - all
registries:
- type: standard
  ref: v4.219.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.56.0
- name: junegunn/fzf@v0.55.0
- name: dandavison/delta@0.18.1
- name: Wilfred/difftastic@0.60.0
- name: rossmacarthur/sheldon@0.7.4
- name: BurntSushi/ripgrep@14.1.1
- name: sharkdp/bat@v0.24.0
- name: starship/starship@v1.20.1
- name: eza-community/eza@v0.19.2
- name: neovim/neovim@v0.10.1
- name: sharkdp/fd@v10.2.0
