[general]
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "HackGen35 Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen35 Console NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "HackGen35 Console NF"
style = "Italic"

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[font.offset]
x = 1
y = 2

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.95
option_as_alt = "OnlyLeft"

[window.padding]
x = 8
y = 16
