packages:
  - type: github_release
    repo_owner: tmux
    repo_name: tmux-builds
    description: tmux builds
    asset: tmux-{{trimV .Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
    format: tar.gz
    files:
      - name: tmux
    replacements:
      amd64: x86_64
      darwin: macos
    supported_envs:
      - linux
      - darwin
