---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
    - all
registries:
  - type: standard
    ref: v4.472.0 # renovate: depName=aquaproj/aqua-registry
  - name: local
    type: local
    path: aqua-registry.yaml
packages:
  # go
  - name: golang/go@go1.26.0
  - name: golang.org/x/tools/gopls@v0.21.1
  - name: go-delve/delve@v1.26.0
  - name: golangci/golangci-lint@v2.9.0
  - name: nametake/golangci-lint-langserver@v0.0.11
  # javascript
  - name: pnpm/pnpm@v10.29.3
  - name: denoland/deno@v2.6.9
  - name: Schniz/fnm@v1.38.1
  # python
  - name: astral-sh/uv@0.10.3
  # git
  - name: cli/cli@v2.86.0
  - name: dandavison/delta@0.18.2
  - name: x-motemen/ghq@v1.9.3
  - name: jesseduffield/lazygit@v0.59.0
  # vim
  - name: neovim/neovim@v0.11.6
  # shell
  - name: starship/starship@v1.24.2
  - name: rossmacarthur/sheldon@0.8.5
  # linters, formatters, language servers
  - name: bufbuild/buf@v1.65.0
  - name: rhysd/actionlint@v1.7.11
  - name: hadolint/hadolint@v2.14.0
  - name: mvdan/sh@v3.12.0
  - name: JohnnyMorganz/StyLua@v2.3.1
  - name: grafana/jsonnet-language-server@v0.17.0
  - name: LuaLS/lua-language-server@3.17.1
  - name: github/copilot-language-server-release@1.430.0
  # CLI for cloud services
  - name: auth0/auth0-cli@v1.27.2
  - name: aws/aws-cli@2.33.23
  - name: stripe/stripe-cli@v1.35.0
  # tools
  - name: junegunn/fzf@v0.67.0
  - name: BurntSushi/ripgrep@15.1.0
  - name: sharkdp/bat@v0.26.1
  - name: eza-community/eza@v0.23.4
  - name: sharkdp/fd@v10.3.0
  - name: direnv/direnv@v2.37.1
  - name: awslabs/git-secrets@1.3.0
  - name: jesseduffield/lazydocker@v0.24.4
  - name: jqlang/jq@jq-1.8.1
  - name: ajeetdsouza/zoxide@v0.9.9
  - name: Wilfred/difftastic@0.67.0
  - name: sxyazi/yazi@v26.1.22
  - name: jorgerojas26/lazysql@v0.4.6
  - name: oven-sh/bun@bun-v1.3.9
  - name: anthropics/claude-code@v2.1.47
  - name: openai/codex@rust-v0.104.0
  - name: tombi-toml/tombi@v0.7.30
  # local
  - name: tmux/tmux-builds@v3.6a
    registry: local
