---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
    - all
registries:
  - type: standard
    ref: v4.454.0 # renovate: depName=aquaproj/aqua-registry
packages:
  # go
  - name: golang/go@go1.25.5
  - name: golang.org/x/tools/gopls@v0.21.0
  - name: go-delve/delve@v1.26.0
  - name: golangci/golangci-lint@v1.64.8
  - name: nametake/golangci-lint-langserver@v0.0.11
  # javascript
  - name: pnpm/pnpm@v10.28.0
  - name: denoland/deno@v2.6.4
  - name: Schniz/fnm@v1.38.1
  # python
  - name: astral-sh/uv@0.9.21
  # git
  - name: cli/cli@v2.83.2
  - name: dandavison/delta@0.18.2
  - name: x-motemen/ghq@v1.8.0
  - name: jesseduffield/lazygit@v0.58.0
  # vim
  - name: neovim/neovim@v0.11.5
  # shell
  - name: starship/starship@v1.24.2
  - name: rossmacarthur/sheldon@0.8.5
  # linters, formatters, language servers
  - name: bufbuild/buf@v1.63.0
  - name: rhysd/actionlint@v1.7.10
  - name: hadolint/hadolint@v2.14.0
  - name: mvdan/sh@v3.12.0
  - name: JohnnyMorganz/StyLua@v2.3.1
  - name: grafana/jsonnet-language-server@v0.16.0
  - name: LuaLS/lua-language-server@3.16.4
  - name: github/copilot-language-server-release@1.409.0
  # CLI for cloud services
  - name: auth0/auth0-cli@v1.25.1
  - name: aws/aws-cli@2.32.29
  - name: stripe/stripe-cli@v1.34.0
  # tools
  - name: junegunn/fzf@v0.67.0
  - name: BurntSushi/ripgrep@15.1.0
  - name: sharkdp/bat@v0.26.1
  - name: eza-community/eza@v0.23.4
  - name: sharkdp/fd@v10.3.0
  - name: direnv/direnv@v2.37.1
  - name: awslabs/git-secrets@1.3.0
  - name: jesseduffield/lazydocker@v0.24.3
  - name: jqlang/jq@jq-1.8.1
  - name: ajeetdsouza/zoxide@v0.9.8
  - name: Wilfred/difftastic@0.67.0
  - name: sxyazi/yazi@v26.1.4
  - name: jorgerojas26/lazysql@v0.4.6
  - name: oven-sh/bun@bun-v1.3.5
