ConfigFile = '/Users/masayuki.izumi/.config/lazysql/config.toml'

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100

[[database]]
Name = 'postgres local'
URL = 'postgres://postgres:password@localhost:5432?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
Commands = []

[[database]]
Name = 'mysql local'
URL = 'mysql://root:password@127.0.0.1:3306'
Provider = 'mysql'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
Commands = []
